name: page_transition
description: Flutter Page Transition Package which is the transition second page
version: 1.1.7+2
homepage: https://github.com/kalismeras61/flutter_page_transition

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter: