name: page_transition
description: Flutter Page Transition Package which is the transition second page
version: 2.0.0-nullsafety.0
homepage: https://github.com/kalismeras61/flutter_page_transition

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3



flutter: